## 仅含有BD

In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets, svm, metrics
from sklearn import cross_validation
import time
def loaddata(Filename):
    data = pd.read_csv(Filename,sep=',',header = None)
    return np.array(data)
# dataset
data1 = loaddata("data0_4.csv")
data2 = loaddata("data1_4.csv")
data3 = loaddata("data2_4.csv")
data4 = loaddata("data3_4.csv")
data5 = loaddata("data4_4.csv")

data_train = np.vstack((data1[:len(data1)-1],data2[:len(data1)]))
data_train = np.vstack((data_train,data3[:len(data1)]))
data_train = np.vstack((data_train,data4[:len(data1)]))
data_train = np.vstack((data_train,data5[:len(data1)]))

print('This is data_train',type(data_train),data_train.shape)
#label
data1 = loaddata("label0_4.csv")
data2 = loaddata("label1_4.csv")
data3 = loaddata("label2_4.csv")
data4 = loaddata("label3_4.csv")
data5 = loaddata("label4_4.csv")

label_train = np.vstack((data1[:len(data1)-1],data2[:len(data1)]))
label_train = np.vstack((label_train,data3[:len(data1)]))
label_train = np.vstack((label_train,data4[:len(data1)]))
label_train = np.vstack((label_train,data5[:len(data1)]))
#print(label_test[100:800])
X_train,X_test,y_train,y_test=cross_validation.train_test_split(data_train,label_train,test_size=0.1)

print('This is X_test',type(X_test),X_test.shape)
print('This is y_test',type(y_test),y_test.shape)
print('This cell has done...')

/home/cadu/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


This is data_train <class 'numpy.ndarray'> (25954, 256)
This is X_test <class 'numpy.ndarray'> (2596, 256)
This is y_test <class 'numpy.ndarray'> (2596, 1)
This cell has done...


In [2]:
#svm
classifier = svm.SVC(gamma=0.001)

timeStart=time.time()
# learn
print('Training starts...')
classifier.fit(X_train, y_train)

timeHalf=time.time()
print('Train train total time is:',timeHalf-timeStart)
#predicted

print('Test starts...')
expected =y_test
predicted=classifier.predict(X_test)
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
timeEnd=time.time()
print('The test time is',timeEnd-timeHalf)

Training starts...


/home/cadu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train train total time is: 413.53499388694763
Test starts...
Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.00      0.00      0.00       508
          1       0.00      0.00      0.00       504
          2       0.19      1.00      0.32       501
          3       0.00      0.00      0.00       540
          4       0.00      0.00      0.00       543

avg / total       0.04      0.19      0.06      2596


Confusion matrix:
[[  0   0 508   0   0]
 [  0   0 504   0   0]
 [  0   0 501   0   0]
 [  0   0 540   0   0]
 [  0   0 543   0   0]]
The test time is 19.121323108673096


/home/cadu/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
