## 含有PL IPT BD

In [2]:
import pandas as pd
import numpy as np
from sklearn import datasets, svm, metrics
from sklearn import cross_validation
import time
def loaddata(Filename):
    data = pd.read_csv(Filename,sep=',',header = None)
    return np.array(data)
# dataset
data1 = loaddata("data0_3.csv")
data2 = loaddata("data1_3.csv")
data3 = loaddata("data2_3.csv")
data4 = loaddata("data3_3.csv")
data5 = loaddata("data4_3.csv")

data_train = np.vstack((data1[:len(data1)-1],data2[:len(data1)]))
data_train = np.vstack((data_train,data3[:len(data1)]))
data_train = np.vstack((data_train,data4[:len(data1)]))
data_train = np.vstack((data_train,data5[:len(data1)]))

print('This is data_train',type(data_train),data_train.shape)
#label
data1 = loaddata("label0_3.csv")
data2 = loaddata("label1_3.csv")
data3 = loaddata("label2_3.csv")
data4 = loaddata("label3_3.csv")
data5 = loaddata("label4_3.csv")

label_train = np.vstack((data1[:len(data1)-1],data2[:len(data1)]))
label_train = np.vstack((label_train,data3[:len(data1)]))
label_train = np.vstack((label_train,data4[:len(data1)]))
label_train = np.vstack((label_train,data5[:len(data1)]))
#print(label_test[100:800])
X_train,X_test,y_train,y_test=cross_validation.train_test_split(data_train,label_train,test_size=0.1)

print('This is X_test',type(X_test),X_test.shape)
print('This is y_test',type(y_test),y_test.shape)
print('This cell has done...')

This is data_train <class 'numpy.ndarray'> (25954, 463)
This is X_test <class 'numpy.ndarray'> (2596, 463)
This is y_test <class 'numpy.ndarray'> (2596, 1)
This cell has done...


In [3]:
#svm
classifier = svm.SVC(gamma=0.001)

timeStart=time.time()
# learn
print('Training starts...')
classifier.fit(X_train, y_train)

timeHalf=time.time()
print('Train train total time is:',timeHalf-timeStart)
#predicted

print('Test starts...')
expected =y_test
predicted=classifier.predict(X_test)
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
timeEnd=time.time()
print('The test time is',timeEnd-timeHalf)

Training starts...


/home/cadu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train train total time is: 788.9964859485626
Test starts...
Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.99      0.62      0.76       513
          1       0.75      0.73      0.74       524
          2       0.50      1.00      0.67       520
          3       0.97      0.74      0.84       514
          4       0.96      0.61      0.75       525

avg / total       0.83      0.74      0.75      2596


Confusion matrix:
[[316   0 189   0   8]
 [  0 384 128  10   2]
 [  0   0 520   0   0]
 [  0  79  53 380   2]
 [  2  51 151   1 320]]
The test time is 24.87376379966736
