In [10]:
import pandas as pd
import numpy as np
from sklearn import datasets, svm, metrics,
from sklearn.cross_validation import train_test_split
import time

In [11]:
def loaddata(Filename):
    data = pd.read_csv(Filename,sep=',',header = None)
    return np.array(data)
# dataset
data1 = loaddata("demo1.csv")
data2 = loaddata("demo2.csv")
data3 = loaddata("demo3.csv")

data_train = np.vstack((data1[:int(len(data1)*0.8)],data2[:int(len(data1)*0.8)]))
data_train = np.vstack((data_train,data3[:int(len(data1)*0.8)]))

data_test = np.vstack((data1[int(len(data1)*0.8):len(data1)-2],data2[int(len(data2)*0.8):len(data2)-2]))
data_test = np.vstack((data_test,data3[int(len(data3)*0.8):len(data3)-2]))

print('This is data_train',type(data_train),data_train.shape)
print('This is data_test',type(data_test),data_test.shape)
#label
data1 = loaddata("label1.csv")
data2 = loaddata("label2.csv")
data3 = loaddata("label3.csv")

label_train = np.vstack((data1[:int(len(data1)*0.8)],data2[:int(len(data1)*0.8)]))
label_train = np.vstack((label_train,data3[:int(len(data1)*0.8)]))


label_test = np.vstack((data1[int(len(data1)*0.8):len(data1)-2],data2[int(len(data2)*0.8):len(data2)-2]))
label_test = np.vstack((label_test,data3[int(len(data3)*0.8):len(data3)-2]))
#print(label_test[100:800])

print('This is label_train',type(label_train),label_train.shape)
print('This is label_test',type(label_test),label_test.shape)



This is data_train <class 'numpy.ndarray'> (12456, 661)
This is data_test <class 'numpy.ndarray'> (37216, 661)
This is label_train <class 'numpy.ndarray'> (12456, 1)
This is label_test <class 'numpy.ndarray'> (37216, 1)


In [13]:
#svm
classifier = svm.SVC(gamma=0.001)

timeStart=time.time()
# learn
print('Training starts...')
classifier.fit(data_train, label_train)

#predicted

print('Test starts...')
expected =label_test
predicted=classifier.predict(data_test)
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
timeEnd=time.time()
print('The total time is',timeEnd-timeStart)

Training starts...


d:\program files\python\lib\site-packages\sklearn\utils\validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Test starts...
Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          1       0.03      1.00      0.05      1037
          2       0.29      0.00      0.00     14352
          3       1.00      0.00      0.00     21827

avg / total       0.70      0.03      0.00     37216


Confusion matrix:
[[ 1037     0     0]
 [14350     2     0]
 [21821     5     1]]
The total time is 474.3523256778717


In [9]:
import random
import numpy as np
a=np.random.rand(12456)
for i in range(0,12456):
    a[i]=i
print(a,a.shape)
b=random.shuffle(a)
print(b.shape)


[  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   1.24530000e+04
   1.24540000e+04   1.24550000e+04] (12456,)


AttributeError: 'NoneType' object has no attribute 'shape'

In [3]:
import pandas as pd
import numpy as np
from sklearn import datasets, svm, metrics
from sklearn import cross_validation
import time
def loaddata(Filename):
    data = pd.read_csv(Filename,sep=',',header = None)
    return np.array(data)
# dataset
data1 = loaddata("demo1.csv")
data2 = loaddata("demo2.csv")
data3 = loaddata("demo3.csv")
data4 = loaddata("demo4.csv")
data5 = loaddata("demo5.csv")

data_train = np.vstack((data1[:len(data1)-1],data2[:len(data1)]))
data_train = np.vstack((data_train,data3[:len(data1)]))
data_train = np.vstack((data_train,data4[:len(data1)]))
data_train = np.vstack((data_train,data5[:len(data1)]))

print('This is data_train',type(data_train),data_train.shape)
#label
data1 = loaddata("label1.csv")
data2 = loaddata("label2.csv")
data3 = loaddata("label3.csv")
data4 = loaddata("label4.csv")
data5 = loaddata("label5.csv")

label_train = np.vstack((data1[:len(data1)-1],data2[:len(data1)]))
label_train = np.vstack((label_train,data3[:len(data1)]))
label_train = np.vstack((label_train,data4[:len(data1)]))
label_train = np.vstack((label_train,data5[:len(data1)]))
#print(label_test[100:800])
X_train,X_test,y_train,y_test=cross_validation.train_test_split(data_train,label_train,test_size=0.1)

print('This is X_test',type(X_test),X_test.shape)
print('This is y_test',type(y_test),y_test.shape)

This is data_train <class 'numpy.ndarray'> (25954, 661)
This is X_test <class 'numpy.ndarray'> (2596, 661)
This is y_test <class 'numpy.ndarray'> (2596, 1)


In [4]:
#svm
classifier = svm.SVC(gamma=0.001)

timeStart=time.time()
# learn
print('Training starts...')
classifier.fit(X_train, y_train)

timeHalf=time.time()
print('Train train total time is:',timeHalf-timeStart)
#predicted

print('Test starts...')
expected =y_test
predicted=classifier.predict(X_test)
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
timeEnd=time.time()
print('The test time is',timeEnd-timeHalf)

Training starts...


/home/cadu/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train train total time is: 908.923876285553
Test starts...
Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.99      0.64      0.78       527
          1       0.77      0.74      0.76       527
          2       0.98      0.66      0.79       519
          3       0.97      0.75      0.85       522
          4       0.50      1.00      0.67       501

avg / total       0.85      0.76      0.77      2596


Confusion matrix:
[[338   0   5   0 184]
 [  0 391   2  12 122]
 [  3  50 342   1 123]
 [  0  66   1 392  63]
 [  0   0   0   0 501]]
The test time is 32.218891620635986


## notebook
- 精度(precision) = 正确预测的个数(TP)/被预测正确的个数(TP+FP)
- 召回率(recall)=正确预测的个数(TP)/预测个数(TP+FN)
- F1 = 2*精度*召回率/(精度+召回率)